name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      
      - name: Check formatting
        run: crystal tool format --check

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [core, lex]
    
    name: Test hecate-${{ matrix.shard }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      
      - name: Cache shards
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/shards
            lib
            shards/hecate-${{ matrix.shard }}/lib
          key: ${{ runner.os }}-shards-latest-${{ matrix.shard }}-${{ hashFiles('**/shard.yml') }}
          restore-keys: |
            ${{ runner.os }}-shards-latest-${{ matrix.shard }}-
            ${{ runner.os }}-shards-latest-
      
      - name: Install dependencies
        run: |
          cd shards/hecate-${{ matrix.shard }}
          shards install
      
      - name: Run tests
        run: |
          cd shards/hecate-${{ matrix.shard }}
          crystal spec --error-on-warnings
      
      - name: Build shard
        run: |
          cd shards/hecate-${{ matrix.shard }}
          crystal build --no-codegen src/hecate-${{ matrix.shard }}.cr

  # Test the monorepo integration
  integration:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      
      - name: Install just
        uses: extractions/setup-just@v2
      
      - name: Cache shards
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/shards
            lib
          key: ${{ runner.os }}-shards-latest-integration-${{ hashFiles('shard.yml', 'shard.dev.yml') }}
          restore-keys: |
            ${{ runner.os }}-shards-latest-integration-
      
      - name: Install all dependencies
        run: just install
      
      - name: Run all tests from root
        run: just test
      
      - name: Check examples build
        run: |
          just example-json
          just example-js
          just example-dynamic

  docs:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      
      - name: Install just
        uses: extractions/setup-just@v2
      
      - name: Install dependencies
        run: |
          cd shards/hecate-core && shards install
          cd ../hecate-lex && shards install
      
      - name: Generate documentation
        run: just docs