name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      
      - name: Check formatting
        run: crystal tool format --check

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        shard: [core, lex]
    
    name: Test hecate-${{ matrix.shard }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      
      - name: Cache shards
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/shards
            lib
            shards/*/lib
          key: ${{ runner.os }}-shards-latest-${{ matrix.shard }}-${{ hashFiles('shard.yml', 'shard.dev.yml', '**/shard.yml') }}
          restore-keys: |
            ${{ runner.os }}-shards-latest-${{ matrix.shard }}-
            ${{ runner.os }}-shards-latest-
      
      - name: Install dependencies
        run: |
          export SHARDS_OVERRIDE=shard.dev.yml
          shards install
      
      - name: Run tests for specific shard
        run: |
          crystal spec shards/hecate-${{ matrix.shard }}/spec --error-on-warnings
      
      - name: Build shard
        run: |
          crystal build --no-codegen shards/hecate-${{ matrix.shard }}/src/hecate-${{ matrix.shard }}.cr

  # Test the monorepo integration
  integration:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      
      - name: Install just
        uses: extractions/setup-just@v2
      
      - name: Cache shards
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/shards
            lib
          key: ${{ runner.os }}-shards-latest-integration-${{ hashFiles('shard.yml', 'shard.dev.yml') }}
          restore-keys: |
            ${{ runner.os }}-shards-latest-integration-
      
      - name: Install all dependencies
        run: |
          export SHARDS_OVERRIDE=shard.dev.yml
          shards install
      
      - name: Run all tests from root
        run: |
          crystal spec shards/hecate-core/spec --error-on-warnings
          crystal spec shards/hecate-lex/spec --error-on-warnings
      
      - name: Check examples build
        run: |
          crystal run shards/hecate-lex/examples/json_lexer.cr -- shards/hecate-lex/examples/sample.json
          crystal run shards/hecate-lex/examples/mini_js_lexer.cr -- shards/hecate-lex/examples/sample.js
          crystal run shards/hecate-lex/examples/dynamic_lexer_demo.cr -- shards/hecate-lex/examples/sample.js

  docs:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      
      - name: Install dependencies
        run: |
          export SHARDS_OVERRIDE=shard.dev.yml
          shards install
      
      - name: Generate documentation
        run: |
          crystal docs shards/hecate-core/src/hecate-core.cr --project-name="Hecate Core" --project-version="0.1.0" --output=docs/hecate-core
          crystal docs shards/hecate-lex/src/hecate-lex.cr --project-name="Hecate Lex" --project-version="0.1.0" --output=docs/hecate-lex